### ISSUE TITLE
Subsystems and Spacecraft vocabulary links are broken

### ISSUE THREAD

**Issue by ashwani99** [HTTP-APIs/hydra-ecosystem-wiki#18]
[Here](https://github.com/HTTP-APIs/hydra-ecosystem-wiki/blob/master/Design.md#use-cases) the links pointing to Subsystems and Spacecraft vocabularies are broken. It needs to be updated.

@Mec-iS Can you point me to the working links please?

**Comment by Mec-iS** [comment]
Thanks. Fixed.
